"""
Django settings for SoundScape project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

##pip install pipdeptree
from pathlib import Path
from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('DJANGO_SECERT_KEY')
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')
SPOTIFY_REDIRECT_URI = os.getenv('SPOTIFY_REDIRECT_URI')
REDIS_LOCATION = os.getenv('REDIS_LOCATION')
EC2_PUBLIC_IP = os.getenv('EC2_PUBLIC_IP')
CHAT_GPT_API_KEY = os.getenv('CHAT_GPT_API_KEY')
CHAT_GPT_PROJECT = os.getenv('CHAT_GPT_PROJECT')
CHAT_GPT_ORGANIZATION = os.getenv('CHAT_GPT_ORGANIZATION')



# SECURITY WARNING: don't run with debug turned on in production!
#Django's debug mode, default option is false
DEBUG = os.getenv('DEBUG', False)

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.elasticbeanstalk.com',
    'exploresoundscape.com',
    EC2_PUBLIC_IP
]

#Enforces all HTTP requests to be redirected to HTTPS
SECURE_SSL_REDIRECT = True

#Configures the header that the proxy uses to indicate requests are HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#Session cookies are only sent over HTTPS connections
SESSION_COOKIE_SECURE = True

#Ensures CSRF cookies are only sent over HTTPS
CSRF_COOKIE_SECURE = True

#Configures the duration (in seconds) that browsers should enforce HTTPS requests
SECURE_HSTS_SECONDS = 31536000  # One year

#Applies HSTS to all subdomains of the website
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

#Site should be preloaded in browsers’ HSTS preload list
SECURE_HSTS_PRELOAD = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Apps.SoundScapeApp',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_extensions',
    'social_django',
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = 'SoundScape.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Apps/SoundScapeApp/Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SoundScape.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import pymysql

pymysql.install_as_MySQLdb()


DATABASE_TYPE = os.getenv('DATABASE_TYPE', 'sqlite').lower()

if DATABASE_TYPE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('AWS_DB_NAME'),
            'USER': os.getenv('AWS_DB_USER'),
            'PASSWORD': os.getenv('AWS_DB_PASSWORD'),
            'HOST': os.getenv('AWS_DB_HOST'),
            'PORT': os.getenv('AWS_DB_PORT'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
            },
        }
    }
else:  # Fallback to SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.getenv('STATIC_ROOT')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


ACCOUNT_ADAPTER = 'Apps.SoundScapeApp.adapters.CustomAccountAdapter'

# General settings
ACCOUNT_AUTHENTICATION_METHOD = "username_email"  # Login by username or email
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "none"  # 'mandatory', 'optional', or 'none'
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SIGNUP_REDIRECT_URL = '/index/'  # Redirect after signup
ACCOUNT_LOGOUT_REDIRECT_URL = '/'  # Redirect after logout


CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_LOCATION,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

SITE_ID = 1

# Allow React dev and prod
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite dev
    "https://yourdomain.com",  # production
]

# API-only: Disable CSRF for API views if needed
CSRF_TRUSTED_ORIGINS = ["https://yourdomain.com"]